version: 0.2

phases:
  pre_build:
    commands:
       - AWS_REGION=$(aws ec2 describe-availability-zones --output text --query 'AvailabilityZones[0].[RegionName]')
  build:
    commands:
       - cd java
       - VERSION=$(grep "version =" build.gradle | awk -F"'" '{print $2}')
       - gradle clean build
       - find build/libs/ -type f \( -name "*.jar" -not -name "*sources.jar" \) -exec cp {} ../docker/app.jar \;
  post_build:
    commands:
       - login_password=$(aws ecr get-login-password --region $AWS_REGION)
       - docker login --username AWS -p $login_password $ECR_URI
       - cd ../docker
       - docker build -t java_app:$VERSION .
       - docker tag java_app:$VERSION $ECR_URI:$VERSION
       - docker push $ECR_URI:$VERSION