version: 0.2

#env:
  #variables:
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"
  #secrets-manager:
     # key: secret-id:json-key:version-stage:version-id
     # key: secret-id:json-key:version-stage:version-id
  #exported-variables:
     # - variable
     # - variable
  #git-credential-helper: yes
#batch:
  #fast-fail: true
  #build-list:
  #build-matrix:
  #build-graph:
phases:
  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  pre_build:
    commands:
       - AWS_REGION=$(aws ec2 describe-availability-zones --output text --query 'AvailabilityZones[0].[RegionName]')
  build:
    commands:
       - cd java
       - VERSION=$(grep "version =" build.gradle | awk -F"'" '{print $2}')
       - gradle clean build
       - find build/libs/ -type f \( -name "*.jar" -not -name "*sources.jar" \) -exec cp {} ../docker/app.jar \;
  post_build:
    commands:
       - login_password=$(aws ecr get-login-password --region $AWS_REGION)
       - docker login --username AWS -p $login_password $ECR_URI
       - cd ../docker
       - docker build -t java_app:$VERSION .
       - docker tag java_app:$VERSION $ECR_URI:$VERSION
       - docker push $ECR_URI:$VERSION
#reports:
  #report-name-or-arn:
    #files:
      # - location
      # - location
    #base-directory: location
    #discard-paths: yes
    #file-format: JunitXml | CucumberJson
#artifacts:
  #files:
    # - location
    # - location
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - paths